### ISSUE TITLE
post image never being displayed.

### ISSUE THREAD

**Issue by awb99** [zutrinken/bleak#39]
I am running the latest ghost version.
The template does not view any "post images" in the overview at all.

**Comment by zutrinken** [comment]
@awb99 just tested it with the latest [version 0.11.9](https://github.com/TryGhost/Ghost/releases/tag/0.11.9) and works fine here. Did you set an image in the [post settings overview](https://help.ghost.org/hc/en-us/articles/223237728-Post-Settings-Overview)?

**Comment by zutrinken** [comment]
@awb99 I just checked the 1.0 beta and there it has to be different. Instead of `{{image}}` you have to use `{{feature_image}}`. So you have to edit the [loop.hbs](https://github.com/zutrinken/bleak/blob/master/partials/loop.hbs) at line `10` and `12`. There are actually even more changes to the `{{image}}` helper, but I'll change the theme when 1.0 is officially out of beta. Until then this theme supports the latest release and no pre-release. I hope that helps and thanks for the report.
