### ISSUE TITLE
Green delimiter coloring transparent image

### ISSUE THREAD

**Issue by rgarrigue** [zutrinken/bleak#7]
Hi

I linked [this image](https://www.git-scm.com/images/logos/downloads/Git-Logo-2Color.png) to a post. As you can see, it's a .png with a transparent background. Displaying in my blog's main page with your theme, the image was colored green. Not exactly the same one as the delimiter, but something like 50%-80% of it.

I fixed this cosmetic issue by downloading the image, painting the transparent part in white and upload it to the blog. But I'ld prefer a link ;-)

Thanks & regards

**Comment by zutrinken** [comment]
Hi @rgarrigue

I definitely see your point, but when it comes to transparent images there’s always the question what is a neutral background color. For the most it is white I guess and also there are a lot that only looks good on black.

I choose the green for the case when the image link is broken. Than the layout doesn’t look that much broken. Since there isn’t that one solution that fits all cases I’d stay with the green background color.

But anyway, thanks for the awareness of this case.

best,
peter
